### ISSUE TITLE
Increased number of macros/layers ?

### ISSUE THREAD

**Issue by Synless** [dhowland/EasyAVR#54]
Hi !
First, thanks for Easy AVR. I just modded a Filco TKL with a Pegasus Hoof and it does wonder.

I wanted to type characters like  _ő è ú í ü_  and other unicodes but currently it is not possible from a US layout. I wish to keep the US layout while being able to print special characters.
I have seen that it was discussed already in [issue 35 about unicode](https://github.com/dhowland/EasyAVR/issues/35), and I thought of a workaround : using Alt+XXXX to print them. But since a lot of macros is required I try to increase the maximum number of macros and layers.

(Disclaimer, I am not great with Python).
I went to guy.py and changed the number of macros from 14 to 16 as a beginning and then I added M15, M16 on the other files while pushing aside some other macros to get some bytes available (from the second parameter of the scancode table).
https://github.com/dhowland/EasyAVR/blob/8a390dbe5475d006a2af9c3107d80a1c2ba10033/keymapper/easykeymap/gui.py#L85
https://github.com/dhowland/EasyAVR/blob/8a390dbe5475d006a2af9c3107d80a1c2ba10033/keymapper/easykeymap/scancodes.py#L304
https://github.com/dhowland/EasyAVR/blob/e3ecba61278e55843f3f20b1ec3c8b4ced51d3fe/keymapper/easykeymap/picker.py#L318
https://github.com/dhowland/EasyAVR/blob/e3ecba61278e55843f3f20b1ec3c8b4ced51d3fe/firmware/src/keymap.c#L1127
https://github.com/dhowland/EasyAVR/blob/e3ecba61278e55843f3f20b1ec3c8b4ced51d3fe/firmware/src/config_keymap.h#L183
But now during the firmware building I have this error :
![image](https://user-images.githubusercontent.com/9463897/36065636-d11378bc-0e9d-11e8-96c3-85cd741ecf87.png)

I will try to work it out but due to my limited knowledge in Python, any help would be appreciated. 
And once again, great piece of software.

**Comment by dhowland** [comment]
Adding more macros to the firmware is more complicated than you think.  It requires a change to the C code.

**Comment by Synless** [comment]
Could you give hints on where to look for ?
Would it be possible to have more macros and layers in the foreseeable future ?
If not, is there any other solutions for unicode on custom controllers you could think of ?

**Comment by dhowland** [comment]
Sorry, I was taking care of a baby when I responded.  I committed a change that demonstrates how to increase the number of macros.  If you want to make your own branch with even *more* macros, you can use the latest code as a base.

Unicode is really an issue for the PC, rather than the keyboard.  They keyboard sends scancodes, not characters.  The PC is responsible for translating the scancodes into characters, and in languages with many diacritics/umlauts/accents/whatever, there are more characters than there are keys.  If you need to enter those characters, you might want to look into internationalization.
