### ISSUE TITLE
Fails to build binary

### ISSUE THREAD

**Issue by Cabalforces** [dhowland/EasyAVR#60]
[Throws this error message](https://imgur.com/a/zKex7)

**Comment by dhowland** [comment]
What is the hardware and layout?  Can you provide the save file?
thanks.

**Comment by Cabalforces** [comment]
It's a teensy, the layout is a numpad with an extra row
[numpad.zip](https://github.com/dhowland/EasyAVR/files/1800791/numpad.zip)

**Comment by dhowland** [comment]
The problem is the definition of the board.  You have this:

```python
num_rows = 6
num_cols = 4
```
And then later you have this:

```python
((4, 4), (0, 6), 'SCANCODE_FN0')],
```
That assigns the key to matrix row index 0 and column index 6.  (that's the 7th column)  There are only 4.

The matrix assignments for all the keys require fixing.

**Comment by Cabalforces** [comment]
Thank you very much for your help, it was driving me crazy. I've read through the whole code at least ten times, and I didn't find the mistake.

**Comment by dhowland** [comment]
No problem, and I commend you for sticking with it.  Because the tool has to support so many different kinds of boards, these files end up being very complicated and few people have managed to understand them.

But you have reminded me that I really need to put a sanity check into the config loader so these common issues are pointed out immediately when you load it.  I'll add that to 3.0.

**Comment by dhowland** [comment]
Quoting from the Geekhack thread:

"if you try and build a COSTAR sized matrix against the FULLSIZE firmware it doesn't work well"

In addition, Pull Request #37 tried to fix this kind of problem a year ago.

Two more data points that show this Issue needs to be fixed.

I'll be adding some defensive code soon.
