### ISSUE TITLE
Access a second layer from a true combination (e.g. `Fn`+`Alt Gr`)

### ISSUE THREAD

**Issue by i5ar** [dhowland/EasyAVR#74]
I access Layer 1 from `Fn 1` key and Layer 2 from the combination `Fn 1`+`Alt Gr` keys.  
In order to access Layer 2, I need to press first `Fn 1` and then `Alt Gr` because `Alt Gr` is `Fn 2` on Layer 1. This solution feels a little hacky because the combination will not works when I press  `Fn 1` and `Alt Gr` with the reverse order or at the same time.  
Is it possible, using Easy AVR, to map a true combination (e.g. `Fn`+`Alt Gr`) to a layer?
Thank you.

**Comment by dhowland** [comment]
How is the keyboard supposed to know that when you press AltGr, you don't actually want to send that scancode, but instead intend to use it as a Function key?

Combinations like the one you describe are possible with custom programming.  EasyAVR's central idea is that you don't have to compile anything yourself.  In order to make it so, the tool must be general purpose.

It's not possible, sorry.  HOWEVER, you can get very close.  You simply copy Layer0 to Layer3, and make it identical except for the Fn1 key, which is changed to Fn2.  Then you replace AltGr with Fn3 with R_Alt mod.  See where I'm going with that?

**Comment by i5ar** [comment]
That's exactly what I was thinking of, just wondering if there was a method to avoid the layer duplication but that's fine anyway. Thank you!
