### ISSUE TITLE
Spurious key events from L_GUI modifier, maybe others too

### ISSUE THREAD

**Issue by mkninc** [dhowland/EasyAVR#79]
L_GUI Key modifier seams to generate additional events.

Steps to reproduce:
1. Press L_GUI
2. Press and release 'E' -> Opens Explorer
3. Release L_GUI -> Windows start menu opens up, should not happen

Version 3.01.01
Hardware: Filco Majestouch Tenkeyless + Pegasus Hoof

Version 3.00.02 works just fine.

**Comment by dhowland** [comment]
Thanks very much for the feedback.  I didn't have a lot of time to test this one.  I'll look at this today.

This could be a problem with the NKRO endpoint.  Can you try it with NKRO disabled?

**Comment by dhowland** [comment]
Okay I have reproduced this problem.  It's not a spurious key event from the keyboard, the keyboard is working as designed.  It's the result of a bad assumption about how Windows interprets multiple keyboards.  

The NKRO support became a separate endpoint in the new version.  The bug is a result of the boot keyboard being used for modifiers and the NKRO endpoint being used for alphanumerics.

Disabling NKRO is a workaround until the next version.

**Comment by dhowland** [comment]
Okay, I coded the solution and it works.
