### ISSUE TITLE
Issue loading old configuration in new client

### ISSUE THREAD

**Issue by pimaxc** [dhowland/EasyAVR#87]
Error message
![2018-07-09 12_51_22-easyavr](https://user-images.githubusercontent.com/2054091/42464406-e9e93298-8376-11e8-822f-5969ce2d3e85.png)

File I cannot load
[Brad.zip](https://github.com/dhowland/EasyAVR/files/2177174/Brad.zip)

**Comment by dhowland** [comment]
Okay so this is an unfortunate result of an old mistake.  The original GH60 Satan config (002) was flawed.  The definition of the matrix contained an error.  The board configuration was fixed, we are on 003 now.  I'm sorry to say that the old configs can't be opened because they wouldn't line up with the new matrix.  You have to recreate it.  Sorry 'bout that.

The error message is useless, that needs to be fixed to explain what happened.
